<a href="https://colab.research.google.com/github/Masehanridegreecollege/Python-mini-project-/blob/main/Introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy-Number python
#Most powerful package-Libarary

#Numpy-Dimensions

#A-One Dimensional Array
#[A,B]|| [A \
#B]-Two Dimensional Array-Row||colum
#Three Dimensional
#Array-storing,Manipulating,similar Data type
#Faster then any mathematical functions
#convinient compared to other packages
#Memory efficiency
#support multi dimensional arras

In [ ]:
#Install numpy-pip3 install numpy|| pip install numpy

In [ ]:
import numpy as np

In [ ]:
#create a numpy array
#1D array
arr1D=np.array([1,2,3,4,5])
print (arr1D)

[1 2 3 4 5]


In [ ]:
#creating 2D array-Matrix
arr2D=np.array([
     [0,0,0],[0,0,0]
])
print(arr2D)

[[0 0 0]
 [0 0 0]]


In [ ]:
#creating arrays with default values

allzeros=np.zeros((2,3))
print(allzeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#creating matrix with all values of elements as'1'
allones=np.ones((2,3))
print(allones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#creating matrix with all values of elements
'constant value-n~full value'
allconstant=np.full((2,3),6)
print(allconstant)

[[6 6 6]
 [6 6 6]]


In [ ]:
#creating an identity matrix -I-squer matrix

identity =np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Identity Matrix - Aii= 1 && Aij=0
#For all A Belongs to R MxN
#Aij-

In [ ]:
#creating random Matrices

#between 0and1
rand1=np.random.rand(3,3) #changed ran1 to rand1
print(rand1)
#between aandb
rand2 =np.random.randint(10,20,(33))
print(rand2)

[[0.92588703 0.03720903 0.36052286]
 [0.1280249  0.90844615 0.34495227]
 [0.4918007  0.17127374 0.81341383]]
[17 15 17 14 13 15 10 12 13 10 17 16 15 11 15 17 17 11 10 10 10 18 19 14
 16 18 17 13 18 19 19 15 13]


In [ ]:
#Array properties
arr=np.array([ [1,2,3,4],[2,3,4,5]])
print(arr)

# shape or array
print(f'\The shape of the array is({arr.shape}')
#size of array
print(f'The size of the array is{arr.size}')
#Data type of array
print(f'The Data type of the array is{arr.dtype}')
#Dimensions of array
print(f'The Dimensions of the array is{arr.ndim}')

[[1 2 3 4]
 [2 3 4 5]]
\The shape of the array is((2, 4)
The size of the array is8
The Data type of the array isint64
The Dimensions of the array is2


In [ ]:
#Indexing and slicing

#Access the elements in 1D Array

arr=np. array([1,2,3,4])
print(arr)
print(arr[3])

#slicing the elements
print(arr[0:3])

#Access the element in 2D array
arr2=np.array([[1,2,3],[2,3,4]])
print(arr2)
print(arr2[1,1])
print(arr2[0,:])#frist row with  all columns
print(arr2[:,0])#frist column with all tows

[1 2 3 4]
4
[1 2 3]
[[1 2 3]
 [2 3 4]]
3
[1 2 3]
[1 2]


In [ ]:
#l1=[]
# [l1.append(_) for_in range(10)]

l1=np.arange(10,-10,-1)

print(l1)

[10  9  8  7  6  5  4  3  2  1  0 -1 -2 -3 -4 -5 -6 -7 -8 -9]


In [ ]:
#Mathematical operations

a=np.array([1,2,3])
b=np.array([3,4,5])

print(f'The sum of a and b is {a+b}')
print(f'The diff of a and b is {a-b}')
print(f'The product of a and b is {a*b}')
print(f'The division of a and b is {a/b}')

The sum of a and b is [4 6 8]
The diff of a and b is [-2 -2 -2]
The product of a and b is [ 3  8 15]
The division of a and b is [0.33333333 0.5        0.6       ]


In [ ]:
#Matrix multiplication
b1=np.array([[1,2,3],[2,3,4]])
b2=np.array([[5,6],[7,8],[1,3]])

#Dot product   ___ product=AB __ A m × n __ B n × p
C=np.dot(b1,b2)
print(C)

[[22 31]
 [35 48]]


In [ ]:
print(b1)

[[1 2 3]
 [2 3 4]]


In [ ]:
print(b2)

[[5 6]
 [7 8]
 [1 3]]


In [ ]:
[
  [22,31],
  [35,48]
]

[[22, 31], [35, 48]]

In [ ]:
import numpy as np

In [ ]:
# Recap
arr=np.array([[1,2,3],[4,5,6]])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
#Dot product-mxn||nxp
arr1=np.random.randint(1,2,(3,1))

In [ ]:
arr1.shape

(3, 1)

In [ ]:
arr.shape
arr1.shape

(3, 1)

In [ ]:
result=np.dot(arr,arr1)

In [ ]:
print(result)

[[ 6]
 [15]]


In [ ]:
r1 = np.random.randint(10,20,(3,3))
print(r1)

[[10 16 18]
 [12 14 13]
 [17 19 15]]


In [ ]:
r2=np.eye(3)
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#r2.I
result2=np.dot(r1,r2)

In [ ]:
print(result2)

[[10. 16. 18.]
 [12. 14. 13.]
 [17. 19. 15.]]


In [ ]:
#M.I=I.M=I

In [ ]:
#A.B!=B.A

In [ ]:
#Mathematical operations
# +-*/
t1=np.random.randint(3,6,(3,3))
t2=np.random.randint(3,6,(3,3))

In [ ]:
print(t1)
print(t2)

[[5 5 3]
 [3 3 5]
 [5 5 4]]
[[5 3 4]
 [3 3 3]
 [5 5 4]]


In [ ]:
t3=t1+t2

In [ ]:
#Matrix multiplication
result=np.dot(arr,arr1)

In [ ]:
#Statistics operations
mean=t3.mean()
mode=t3.max()
median=np.median(t3)
std=np.std(t3)
var=np.var(t3)

In [ ]:
print(mean)

8.11111111111111


In [ ]:
print(max)

<built-in function max>


In [ ]:
print(median)

8.0


In [ ]:
print(std)

1.5234788000891208


In [ ]:
print(var)

2.3209876543209877


In [ ]:
std*std

2.3209876543209873

In [ ]:
#Trignometry functions
#Sin(x)
#Cos(x)
#Tan(x)-sin(x)/cos(x)
#Cosec-1/sin(x)
#Sec-1/cos(x)
#Cot-1/Tan(x)
#
angles=np.array([0,15,30,45,60,75,90])
#sin(array)
result=np.sin(np.radians(angles))
result1=np.cos(np.radians(angles))
result2=np.tan(np.radians(angles))

In [ ]:
arr=np.array([1,2,3,4,5,6])
#Reshape the array
reshapeedarr=arr.reshape(2,3)
print(reshapeedarr)
#convert/flatten any n dim array
flattendarr=arr.flatten()
print(flattendarr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
#Stacking the data

arr1=np.array([1,2,3,4])
arr2=np.array([10,20,30,40])

#vertical  stacking
arr3=np.vstack((arr1,arr2))
print(f"The shape of arr3 is {arr3.shape}")

#Horizontal stacking
arr4=np.hstack((arr1,arr2))
print(f"The shape of arr4 is {arr4.shape}")
print(arr4)

The shape of arr3 is (2, 4)
The shape of arr4 is (8,)
[ 1  2  3  4 10 20 30 40]


In [ ]:
#filtaring
arr=np.array([10,20,30,40,50])
farr=arr[arr<40]
print(farr)

[10 20 30]
